<?php


namespace ScandiPWA\Sitemap\Model;


use Magento\Framework\UrlInterface;
use Magento\Sitemap\Model\Sitemap as MagentoSitemap;

class Sitemap extends MagentoSitemap
{
    protected function _getUrl($url, $type = UrlInterface::URL_TYPE_WEB)
    {
        return parent::_getUrl($url, $type); // TODO: Change the autogenerated stub
    }
}